title: opinionated-meteor-application-template
description: An opinionated template for quickly starting Meteor application development
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
